### ISSUE TITLE
Determine Routes for Site

### ISSUE THREAD

**Issue by pantheman1** [RobertVogue/Passport#11]
### Tasks:
- [ ] Review user stories and identify each page we will need for the site
- [ ] Come up with the specific routes
- [ ] Enter these into the Wiki with any necessary explanations

## Routes
- /
- /users/login
- /stamps/create
- users/:id (profile page)
- /users/signup
- /users/:id/stamps/:id (view stamps page)
