### ISSUE TITLE
User Auth Back End

### ISSUE THREAD

**Issue by pantheman1** [RobertVogue/Passport#5]
## Subtasks
- [x] Set up login functionality
- [x] Set up logout functionality
- [x] Set up cookies/session persistence
- [x] Create demo user login
