### ISSUE TITLE
Front End User Auth

### ISSUE THREAD

**Issue by pantheman1** [RobertVogue/Passport#6]
## Subtasks
- [x] Create login form in Pug
- [x] Create registration Pug file
- [x] Style login/registration
