### ISSUE TITLE
User Auth Styling

### ISSUE THREAD

**Issue by pantheman1** [RobertVogue/Passport#7]
## Subtasks
- [x] CSS tasks...
- [x] Decide color pallet and make changes
- [x] Ensure Log-in button reveals sign-in form
- [x] Ensure Sign-up button reveals sign-up form
